server:
  port: 8081

spring:
  data:
    mongodb:
      username: dev
      password: x5etxXQTC29HpS7KU3p87m
      host: 10.8.0.1
      authentication-database: admin

  kafka:
    bootstrap-servers: 10.8.0.1:9092
    consumer:
      group-id: OfficialServer
    template:
      default-topic: tasks